### ISSUE TITLE
cubx-maps-demo: Remove the need for embedding scripts into the target page

### ISSUE THREAD

**Issue by hrbu** [iCubbles/cubx-maps#6]
Currently when embedding the `cubx-maps-demo` component into a webpage, an additional script is required to define the function to be passed into the `markersMapFunction` slot. 

Let's implement another solution, as we don't want to force page-editors to add an addtional `<script>` to the page.

## Proposal
1. Add a `js` file to the `cubx-maps-demo`, that add the function to the global scope
   ```cubx_maps.markersMapFunction = function(value) {...}```
2. Init the `markersMapper.mappterFunction` slot with the name of the global function.

This should do the job for now. 

> Btw. Another approach would be a dedicated `mapperFunctionGenerator` component, that propagates the function via an output slot. A number of inputSlot could be defined to customize the function intially (or dynamically) ... ;-)

**Comment by edwingamboa** [comment]
@hrbu I implemented the initial proposal since I didn't understand so well the idea about the `mapperFunctionGenerator` component. Can you give additional details of what you thought, so that we can test? (e.g. what kind of inputSlots?)
